Default: &defaults
  host: "127.0.0.1"
  port: 3000

Development:
  <<: *defaults
  approot: "http://localhost:3000"

Test:
  <<: *defaults
  approot: "http://localhost:3000"

Staging:
  <<: *defaults
  approot: "http://localhost:3000"

Production:
  <<: *defaults
  approot: "http://rentersreality.com"
